/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskInput = IDL.Record({
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'reminder' : IDL.Opt(IDL.Int),
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'priority' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
  'title' : IDL.Text,
  'assignedTo' : IDL.Opt(IDL.Principal),
  'reminder' : IDL.Opt(IDL.Int),
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Principal,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'priority' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  }),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RoleView = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'taskId' : IDL.Opt(IDL.Nat),
  'message' : IDL.Text,
});
export const ActivityLog = IDL.Record({
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'taskId' : IDL.Nat,
  'timestamp' : IDL.Int,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'taskId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCompletedTasks' : IDL.Func([], [], []),
  'clearOldNotifications' : IDL.Func([], [], []),
  'createNotification' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'createTask' : IDL.Func([TaskInput], [IDL.Nat], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMembers' : IDL.Func([], [IDL.Vec(RoleView)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTaskActivityLog' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityLog)], ['query']),
  'getTaskComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getTasksByAssignee' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'markTaskComplete' : IDL.Func([IDL.Nat], [], []),
  'markTaskPending' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTask' : IDL.Func([IDL.Nat, TaskInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskInput = IDL.Record({
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'reminder' : IDL.Opt(IDL.Int),
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'priority' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'completed' : IDL.Null }),
    'title' : IDL.Text,
    'assignedTo' : IDL.Opt(IDL.Principal),
    'reminder' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Principal,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'priority' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'medium' : IDL.Null,
    }),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RoleView = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'taskId' : IDL.Opt(IDL.Nat),
    'message' : IDL.Text,
  });
  const ActivityLog = IDL.Record({
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'taskId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'taskId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCompletedTasks' : IDL.Func([], [], []),
    'clearOldNotifications' : IDL.Func([], [], []),
    'createNotification' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'createTask' : IDL.Func([TaskInput], [IDL.Nat], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMembers' : IDL.Func([], [IDL.Vec(RoleView)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTaskActivityLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ActivityLog)],
        ['query'],
      ),
    'getTaskComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getTasksByAssignee' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'markTaskComplete' : IDL.Func([IDL.Nat], [], []),
    'markTaskPending' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTask' : IDL.Func([IDL.Nat, TaskInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };