/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityLog {
  'action' : string,
  'userId' : Principal,
  'taskId' : bigint,
  'timestamp' : bigint,
}
export interface Comment {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'text' : string,
  'taskId' : bigint,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : bigint,
  'read' : boolean,
  'taskId' : [] | [bigint],
  'message' : string,
}
export interface RoleView { 'principal' : Principal, 'role' : UserRole }
export interface Task {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'completed' : null },
  'title' : string,
  'assignedTo' : [] | [Principal],
  'reminder' : [] | [bigint],
  'createdAt' : bigint,
  'createdBy' : Principal,
  'dueDate' : bigint,
  'description' : string,
  'updatedAt' : bigint,
  'priority' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
}
export interface TaskInput {
  'title' : string,
  'assignedTo' : [] | [Principal],
  'reminder' : [] | [bigint],
  'dueDate' : bigint,
  'description' : string,
  'priority' : { 'low' : null } |
    { 'high' : null } |
    { 'medium' : null },
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCompletedTasks' : ActorMethod<[], undefined>,
  'clearOldNotifications' : ActorMethod<[], undefined>,
  'createNotification' : ActorMethod<
    [Principal, string, [] | [bigint]],
    undefined
  >,
  'createTask' : ActorMethod<[TaskInput], bigint>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMembers' : ActorMethod<[], Array<RoleView>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyTasks' : ActorMethod<[], Array<Task>>,
  'getTaskActivityLog' : ActorMethod<[bigint], Array<ActivityLog>>,
  'getTaskComments' : ActorMethod<[bigint], Array<Comment>>,
  'getTasksByAssignee' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'markTaskComplete' : ActorMethod<[bigint], undefined>,
  'markTaskPending' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTask' : ActorMethod<[bigint, TaskInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];